export type NodeType = 'start' | 'minor' | 'notable' | 'keystone';
export type Axis = 'perception' | 'reasoning' | 'memory' | 'action' | 'identity';
export interface AgentConfigContribution { tools?: string[]; model?: string; systemPromptAdditions?: string[]; capabilities?: string[]; notes?: string[]; }
export interface TreeNode { id: string; x: number; y: number; type: NodeType; axis?: Axis; label: string; desc?: string; practice: string; config?: AgentConfigContribution; }
export interface TreeEdge { from: string; to: string; }
export interface Synergy { id: string; name: string; requires: string[]; desc: string; bonus?: AgentConfigContribution; }
const C = { x: 500, y: 450 };
const axes: Record<Axis, number> = { perception: -90, reasoning: -18, action: 54, identity: 126, memory: 198 };
const polar = (axis: Axis, r: number) => { const a = (axes[axis] * Math.PI) / 180; return { x: Math.round(C.x + Math.cos(a) * r), y: Math.round(C.y + Math.sin(a) * r) }; };
const n = (id: string, axis: Axis, r: number, type: NodeType, label: string, desc: string, practice: string, config?: AgentConfigContribution): TreeNode => ({ id, axis, type, label, desc, practice, config, ...polar(axis, r) });
export const NODES: Record<string, TreeNode> = {
  birth: { id: 'birth', x: 500, y: 450, type: 'start', label: 'Base Agent', desc: 'The spawn point: a frontier model, a task, and enough context to begin.', practice: 'Pick a frontier model: claude-sonnet-4, gpt-4o-mini, or gemini-2.5-flash. The cheapest capable model is your spawn.', config: { model: 'claude-sonnet-4', systemPromptAdditions: ['You are a helpful agent. Act carefully, use tools when needed, and keep the user informed.'] } },

  p1: { id:'p1', x:500, y:380, type:'minor', axis:'perception', label:'Streaming responses', desc:'Renders tokens as they arrive for conversational UX.', practice:'Enable stream: true on your API calls. Renders tokens as they arrive. Required for any conversational UX.', config:{capabilities:['streaming_responses']} },
  p2: { id:'p2', x:500, y:320, type:'minor', axis:'perception', label:'Structured input', desc:'Validated schemas for safer, more reliable model inputs.', practice:'Define input schemas with JSON Schema or Zod. Validate before passing to the model. Prevents prompt injection from malformed payloads.', config:{capabilities:['structured_input'], notes:['Use JSON Schema or Zod for tool/input validation.']} },
  pN: { id:'pN', x:500, y:260, type:'notable', axis:'perception', label:'Document parsing', desc:'Reads PDFs, Word docs, slides, sheets natively.', practice:"Use Claude's native PDF support (pass PDF base64 to the API) or add Unstructured.io / Reducto for layout-aware extraction.", config:{tools:['mcp:pdf'], capabilities:['document_parsing']} },
  p3: { id:'p3', x:500, y:200, type:'minor', axis:'perception', label:'Vision', desc:'Sees and reasons over images.', practice:'Switch to a vision-capable model. Pass images as base64 in the message content array. Sonnet 4, GPT-4o, Gemini 2.5 all work.', config:{capabilities:['vision']} },
  p4: { id:'p4', x:500, y:140, type:'minor', axis:'perception', label:'Audio input', desc:'Accepts speech or audio by transcription or native multimodal input.', practice:'Add Whisper (OpenAI) or Deepgram for speech-to-text. Or use a natively multimodal model that accepts audio.', config:{tools:['mcp:asr'], capabilities:['audio_input']} },
  pK: { id:'pK', x:500, y:80, type:'keystone', axis:'perception', label:'Multimodal Native', desc:'Accepts text, images, audio, video in the same context.', practice:'Use a fully multimodal model: Claude Opus 4, GPT-4o, or Gemini 2.5 Pro. Send mixed media in one request, no separate transcription step.', config:{model:'claude-opus-4', capabilities:['multimodal_native','vision','audio_input','video_input']} },

  r1: { id:'r1', x:567, y:428, type:'minor', axis:'reasoning', label:'Chain of thought', desc:'Makes reasoning explicit before finalizing.', practice:"Add 'think step by step before answering' to your system prompt, or use a model with built-in thinking mode.", config:{capabilities:['step_by_step_reasoning']} },
  r2: { id:'r2', x:624, y:410, type:'minor', axis:'reasoning', label:'Self-critique', desc:'A second pass catches obvious errors before response.', practice:'After generating, prompt the model to critique its own output and revise. Two-pass costs more but catches obvious errors.', config:{capabilities:['self_critique']} },
  rN: { id:'rN', x:681, y:391, type:'notable', axis:'reasoning', label:'ReAct loop', desc:'Interleaves thought, action, observation across turns.', practice:"Use the ReAct pattern in your agent loop. Thought, Action, Observation, repeat. Most agent frameworks (LangGraph, Anthropic's agent SDK) implement this.", config:{capabilities:['react_loop'], systemPromptAdditions:['Use a ReAct loop when tools are needed: reason, act, observe, then continue.']} },
  r3: { id:'r3', x:738, y:373, type:'minor', axis:'reasoning', label:'Planning', desc:'Plans first, then executes stepwise.', practice:'Have the model emit a plan first (numbered steps), then execute each. Plan visible to user, can be edited mid-stream.', config:{capabilities:['planning']} },
  r4: { id:'r4', x:795, y:354, type:'minor', axis:'reasoning', label:'Tree of thought', desc:'Explores multiple candidate reasoning paths.', practice:'Generate multiple reasoning branches in parallel, score with a verifier model, keep the best. Expensive but powerful for hard problems.', config:{capabilities:['tree_of_thought']} },
  rK: { id:'rK', x:852, y:336, type:'keystone', axis:'reasoning', label:'Extended Thinking', desc:'Deep reasoning mode. High latency, much higher quality on hard problems.', practice:'Use Claude with extended thinking enabled, or OpenAI o3. Set thinking_budget high. Expect 30-120s per response. Worth it for analysis, math, code.', config:{model:'claude-opus-4', capabilities:['extended_thinking']} },

  m1: { id:'m1', x:541, y:507, type:'minor', axis:'memory', label:'Long context', desc:'Keeps more working material in active context.', practice:'Use a model with 200K+ context. Claude family is 200K, Gemini is 1M+. Costs more per token but handles whole-document analysis.', config:{capabilities:['long_context']} },
  m2: { id:'m2', x:576, y:555, type:'minor', axis:'memory', label:'Conversation summary', desc:'Compresses older turns while preserving narrative.', practice:'Periodically summarize older turns and replace them. Keeps the active context lean while preserving narrative.', config:{capabilities:['conversation_summary']} },
  mN: { id:'mN', x:612, y:604, type:'notable', axis:'memory', label:'Vector RAG', desc:'Retrieves relevant context from an external store before each turn.', practice:'Add Postgres + pgvector, or Pinecone / Chroma. Embed your docs with text-embedding-3-small. Retrieve top-k, prepend to system prompt.', config:{tools:['mcp:postgres','mcp:pgvector'], capabilities:['vector_rag']} },
  m3: { id:'m3', x:647, y:652, type:'minor', axis:'memory', label:'Message history', desc:'Persists conversation logs and rehydrates context.', practice:'Persist messages to Postgres. Pass back as the messages array on each request. Standard chatbot memory.', config:{tools:['mcp:postgres'], capabilities:['message_history']} },
  m4: { id:'m4', x:682, y:701, type:'minor', axis:'memory', label:'User profile', desc:'Stores stable preferences, boundaries, and facts.', practice:'Maintain a structured user profile that the agent reads and updates. Stored as JSONB in your DB.', config:{capabilities:['user_profile'], systemPromptAdditions:['Read and respect the structured user profile when available.']} },
  mK: { id:'mK', x:718, y:749, type:'keystone', axis:'memory', label:'Persistent State', desc:'Knows the world develops over time. Reconnects mid-conversation.', practice:'Combine vector store + structured user profile + summary memory + conversation log. Use a memory framework (mem0, Letta) or build your own. Agent feels continuous across sessions.', config:{tools:['mcp:postgres','mcp:pgvector'], capabilities:['persistent_state','semantic_memory','profile_memory']} },

  a1: { id:'a1', x:459, y:507, type:'minor', axis:'action', label:'Tool calling', desc:'Models emit structured tool calls for your runtime to execute.', practice:'Define tools in your API request. Anthropic and OpenAI both have native tool-use. The model emits structured tool_use blocks, you execute, return results.', config:{capabilities:['tool_calling']} },
  a2: { id:'a2', x:424, y:555, type:'minor', axis:'action', label:'Code execution', desc:'Runs code in a sandbox for analysis and data work.', practice:"Add a sandboxed Python interpreter. E2B, Modal, or Anthropic's code execution tool. Critical for data work.", config:{tools:['mcp:code_execution'], capabilities:['code_execution']} },
  aN: { id:'aN', x:388, y:604, type:'notable', axis:'action', label:'MCP servers', desc:'Modular capability layer. Hundreds of community connectors.', practice:'Install Model Context Protocol servers (filesystem, github, postgres, gmail, etc). Mount them in your agent runtime. claude-mcp.com has a registry.', config:{tools:['mcp:filesystem','mcp:github','mcp:postgres'], capabilities:['mcp_servers']} },
  a3: { id:'a3', x:353, y:652, type:'minor', axis:'action', label:'Web search', desc:'Finds live information on the web.', practice:"Add a web search tool. Brave, Tavily, Perplexity, or Anthropic's native web search.", config:{tools:['mcp:web_search'], capabilities:['web_search']} },
  a4: { id:'a4', x:318, y:701, type:'minor', axis:'action', label:'Browser automation', desc:'Controls a browser to operate websites and SPAs.', practice:'Give it a browser via Playwright MCP, Browserbase, or Computer Use. Now it can fill forms, scrape SPAs, take actions on websites.', config:{tools:['mcp:browser'], capabilities:['browser_automation']} },
  aK: { id:'aK', x:282, y:749, type:'keystone', axis:'action', label:'Autonomous Operator', desc:'Full agentic loop. Plans, calls tools, observes, adapts. No human in loop per turn.', practice:'Use an agent framework (Claude Code, LangGraph, OpenAI Agents SDK). Give it a goal and a tool budget. Add guardrails and approval gates for irreversible actions.', config:{tools:['mcp:filesystem','mcp:github','mcp:browser','mcp:postgres'], capabilities:['autonomous_operator'], systemPromptAdditions:['Run a full agentic loop when appropriate: plan, act, observe, adapt. Require approval for irreversible actions.']} },
  i1: { id:'i1', x:433, y:428, type:'minor', axis:'identity', label:'System prompt', desc:'Defines role, capabilities, refusals, and output shape.', practice:'Write a clear 200-500 token system prompt. Define role, capabilities, refusals, output format. This is the lowest-effort highest-leverage move.', config:{systemPromptAdditions:['Follow a clear system prompt defining role, capabilities, refusals, and output format.']} },
  i2: { id:'i2', x:376, y:410, type:'minor', axis:'identity', label:'Persona', desc:'A specific name, voice, and taste profile.', practice:"Give it a name, voice, and a few opinions. Be specific. 'Helpful assistant' is a tell that you didn't bother.", config:{capabilities:['persona'], systemPromptAdditions:['Maintain a specific voice and set of useful opinions.']} },
  iN: { id:'iN', x:319, y:391, type:'notable', axis:'identity', label:'Skills', desc:'Modular markdown capabilities loaded on demand.', practice:"Use Anthropic's Skills format. Write SKILL.md files for repeat tasks. The agent loads them when a triggering query comes in. Composable and inspectable.", config:{tools:['skill:anthropic_skills'], capabilities:['skills']} },
  i3: { id:'i3', x:262, y:373, type:'minor', axis:'identity', label:'Constitution', desc:'Principles for hard cases and drift prevention.', practice:"Define principles for hard cases. 'Never do X. Always do Y. When unsure, prefer Z.' Constitutional AI patterns. Prevents drift.", config:{capabilities:['constitution'], systemPromptAdditions:['Follow explicit principles for hard cases: never do forbidden actions, always preserve safety, and choose the safer path when unsure.']} },
  i4: { id:'i4', x:205, y:354, type:'minor', axis:'identity', label:'Few-shot examples', desc:'Examples that lock in behavior and formatting.', practice:'Show the model 2 to 5 examples of ideal input/output pairs in the system prompt. Format adherence improves dramatically.', config:{capabilities:['few_shot_examples']} },
  iK: { id:'iK', x:148, y:336, type:'keystone', axis:'identity', label:'Distinct Character', desc:'Consistent identity across sessions. Recognizably the same agent.', practice:'Combine persona + constitution + skills + few-shot + memory. The agent has opinions, a voice, and remembers what it values.', config:{capabilities:['distinct_character','stable_identity'], systemPromptAdditions:['Be recognizably the same agent across sessions: consistent voice, values, boundaries, and taste.']} },

  pra: { id:'pra', x:548, y:348, type:'minor', label:'Layout-aware parsing', desc:'Preserves document structure like tables, columns, and sections.', practice:'Use Reducto or Unstructured for tables and complex PDFs. Generic PDF-to-text loses structure.', config:{tools:['mcp:reducto','mcp:unstructured'], capabilities:['layout_aware_parsing']} },
  prN: { id:'prN', x:590, y:365, type:'notable', label:'Doc QA', desc:'Answers questions over a document with citations.', practice:'Combine vision parsing with chain of thought. For each answer, the model emits the source page or section.', config:{capabilities:['document_qa','citations']} },
  prc: { id:'prc', x:618, y:388, type:'minor', label:'Citation tracking', desc:'Makes source references part of the answer contract.', practice:'Make citations part of the output schema. Refuse to answer if no source found.', config:{capabilities:['citation_tracking'], systemPromptAdditions:['Include citations when answering from documents; refuse document claims without a source.']} },
  rma: { id:'rma', x:635, y:450, type:'minor', label:'Scratchpad', desc:'Writable working memory for intermediate findings.', practice:'Give the agent a writable scratchpad in context. It writes intermediate findings, reads them back. Free working memory.', config:{capabilities:['scratchpad']} },
  rmN: { id:'rmN', x:645, y:495, type:'notable', label:'Plan-execute-reflect', desc:'Three-phase loop with memory between phases.', practice:'Phase 1: plan stored in state. Phase 2: execute step by step. Phase 3: reflect on outcome, update memory. LangGraph models this cleanly.', config:{capabilities:['plan_execute_reflect']} },
  rmc: { id:'rmc', x:615, y:540, type:'minor', label:'Learning over time', desc:'Stores what worked and what failed for future sessions.', practice:"After each session, summarize what worked / what didn't. Store as agent memory. Next session reads it first.", config:{capabilities:['learning_over_time']} },

  maA: { id:'maA', x:532, y:595, type:'minor', label:'State checkpoints', desc:'Recoverable snapshots between tool calls.', practice:'Save full state between tool calls. Recoverable from any step. Critical for long-running workflows.', config:{capabilities:['state_checkpoints']} },
  maN: { id:'maN', x:500, y:615, type:'notable', label:'Workflow state machine', desc:'Enforced transitions, restartable, observable.', practice:'Use LangGraph, Inngest, or Temporal. State transitions are explicit, retries are automatic, you can replay.', config:{tools:['framework:langgraph','framework:inngest','framework:temporal'], capabilities:['workflow_state_machine']} },
  maC: { id:'maC', x:468, y:595, type:'minor', label:'Result caching', desc:'Caches repeated tool results to save money and latency.', practice:"Cache tool outputs by input hash. Don't re-fetch the same web page twice. Saves money and latency.", config:{capabilities:['result_caching']} },

  aiA: { id:'aiA', x:385, y:540, type:'minor', label:'Tool descriptions', desc:'Precise tool affordances improve tool choice.', practice:'Write clear, specific descriptions for every tool. The model decides what to call based on these. Vague descriptions = wrong tool picks.', config:{capabilities:['tool_descriptions']} },
  aiN: { id:'aiN', x:358, y:495, type:'notable', label:'Approval gates', desc:'Stops for human review before irreversible actions.', practice:"Mark certain tools as 'requires_approval'. Agent must explicitly request, user must confirm. Use for sends, deletes, payments.", config:{capabilities:['approval_gates'], systemPromptAdditions:['For tools marked requires_approval, stop and request explicit user confirmation before proceeding.']} },
  aiC: { id:'aiC', x:368, y:450, type:'minor', label:'Refusal patterns', desc:'Clear no-go behavior with useful explanations.', practice:"Define what the agent won't do and why. Refuse gracefully with reasons, not error messages.", config:{capabilities:['refusal_patterns'], systemPromptAdditions:['Refuse disallowed actions gracefully with a brief reason and a safe alternative when possible.']} },

  ipA: { id:'ipA', x:385, y:388, type:'minor', label:'Style examples', desc:'Few-shot examples of brand voice and rhythm.', practice:'Show 3 to 5 examples of your brand voice in the system prompt. Tone, vocabulary, sentence rhythm.', config:{capabilities:['style_examples']} },
  ipN: { id:'ipN', x:412, y:365, type:'notable', label:'Multimodal voice', desc:'Same character across text, voice, image, video output.', practice:'Define voice for TTS (ElevenLabs voice ID), visual style for image gen (style reference + lora), tone for text. One identity, all channels.', config:{tools:['mcp:tts','mcp:image_generate','mcp:video_generate'], capabilities:['multimodal_voice']} },
  ipC: { id:'ipC', x:452, y:348, type:'minor', label:'Channel calibration', desc:'Adapts register to the surface and audience.', practice:'Adjust formality based on context. Slack DM vs investor email vs SMS. Detect channel from metadata, switch register.', config:{capabilities:['channel_calibration'], systemPromptAdditions:['Calibrate tone and formality to the channel, audience, and context metadata.']} },

};
export const EDGES: TreeEdge[] = [
  {from:'birth', to:'p1'}, {from:'birth', to:'r1'}, {from:'birth', to:'m1'}, {from:'birth', to:'a1'}, {from:'birth', to:'i1'},
  {from:'p1',to:'p2'},{from:'p2',to:'pN'},{from:'pN',to:'p3'},{from:'p3',to:'p4'},{from:'p4',to:'pK'},
  {from:'r1',to:'r2'},{from:'r2',to:'rN'},{from:'rN',to:'r3'},{from:'r3',to:'r4'},{from:'r4',to:'rK'},
  {from:'m1',to:'m2'},{from:'m2',to:'mN'},{from:'mN',to:'m3'},{from:'m3',to:'m4'},{from:'m4',to:'mK'},
  {from:'a1',to:'a2'},{from:'a2',to:'aN'},{from:'aN',to:'a3'},{from:'a3',to:'a4'},{from:'a4',to:'aK'},
  {from:'i1',to:'i2'},{from:'i2',to:'iN'},{from:'iN',to:'i3'},{from:'i3',to:'i4'},{from:'i4',to:'iK'},
  {from:'p2',to:'pra'},{from:'pra',to:'prN'},{from:'prN',to:'prc'},{from:'prc',to:'r2'},
  {from:'r2',to:'rma'},{from:'rma',to:'rmN'},{from:'rmN',to:'rmc'},{from:'rmc',to:'m2'},
  {from:'m2',to:'maA'},{from:'maA',to:'maN'},{from:'maN',to:'maC'},{from:'maC',to:'a2'},
  {from:'a2',to:'aiA'},{from:'aiA',to:'aiN'},{from:'aiN',to:'aiC'},{from:'aiC',to:'i2'},
  {from:'i2',to:'ipA'},{from:'ipA',to:'ipN'},{from:'ipN',to:'ipC'},{from:'ipC',to:'p2'},
];
export const SYNERGIES: Synergy[] = [
  { id: 'researcher', name: 'Research Analyst', requires: ['pK','rK'], desc: 'Reads any document, thinks deeply about it. Slow, expensive, definitive.' },
  { id: 'strategist', name: 'Strategist', requires: ['rK','mK'], desc: 'Reasons across long timelines and remembers what it concluded.' },
  { id: 'operations', name: 'Operations Agent', requires: ['mK','aK'], desc: 'Runs ongoing workflows without supervision. Improves over time.' },
  { id: 'employee', name: 'Defined Agent', requires: ['aK','iK'], desc: 'Acts in the world with consistent values. The employee archetype.' },
  { id: 'customer', name: 'Brand Voice', requires: ['iK','pK'], desc: 'Has a voice, can see and hear customers, present in any channel.' },
  { id: 'ambient', name: 'Ambient Assistant', requires: ['pK','mK'], desc: 'Watches, listens, remembers. Like a household AI.' },
  { id: 'companion', name: 'Companion', requires: ['mK','iK'], desc: 'Same agent over years. Grows with you.' },
  { id: 'researcher2', name: 'Investigator', requires: ['rK','aK'], desc: 'Plans long investigations, executes them with tools.' },
  { id: 'embodied', name: 'Embodied Agent', requires: ['pK','aK'], desc: 'Robot, AR glasses, screen recorder. Acts on what it perceives.' },
  { id: 'advisor', name: 'Advisor', requires: ['rK','iK'], desc: 'Thinks hard, has clear opinions, stays in character.' },
  { id: 'agi', name: 'General Agent', requires: ['pK','rK','mK','aK','iK'], desc: 'All five keystones. Statistically improbable. The AGI build.' },
];
